from pathlib import Path

BASE_DIR = Path(r"C:\FX\fx_tool")
DATA_DIR = BASE_DIR / "data"
DEFAULT_CSV = DATA_DIR / "USDJPY_5min_2021-2026.csv"
OUTPUT_DIR = DATA_DIR / "research_master_project"

SPREADS = [0.2, 0.5, 1.0, 1.5]
PIP_SIZE = 0.01
INITIAL_BALANCE = 1_000_000
YEN_PER_PIP = 1000

# 6.2で残った本命候補
SESSION_START_HOUR = 16
SESSION_END_HOUR = 21
BREAKOUT_LOOKBACK = 12
EXIT_BARS = 24
DIRECTION = "LONG"

# OOS固定検証
TRAIN_END_YEAR = 2024
OOS_START_YEAR = 2025


# 10.0 Portfolio Lab
MONTE_CARLO_RUNS = 2000
MONTE_CARLO_SEED = 1021
ROLLING_TRAIN_YEARS = 2
ROLLING_TEST_YEARS = 1
MAX_RISK_PCT = 20.0
POSITION_METHODS = ["fixed", "half_kelly", "vol_adjusted"]
